# Directorios

ODOO_CONFIG_DIR="/etc/odoo"
ODOO_CONFIG_REQUIRED="required"

ODOO_FILESTORE_DIR="/var/lib/odoo/filestore"
ODOO_FILESTORE_REQUIRED="required"

ODOO_ADDONS_DIR="/opt/odoo/addons"
ODOO_ADDONS_REQUIRED="required"

ODOO_ADMIN_DIR="/opt/odoo-admin"
ODOO_ADMIN_REQUIRED="required"

# Respaldos

BACKUP_ROOT="/var/backups/odoo"

DAILY_DIR="$BACKUP_ROOT/daily"

WEEKLY_DIR="$BACKUP_ROOT/weekly"

MONTHLY_DIR="$BACKUP_ROOT/monthly"

TARGET_DIR="$DAILY_DIR"

BACKUP_PREFIX="filesystem"

DATE_FORMAT="+%Y-%m-%d_%H-%M-%S"

RETENTION_DAILY=7
RETENTION_WEEKLY=4
RETENTION_MONTHLY=12
