# ============================================================
# PostgreSQL Configuration
# ============================================================

DB_NAME="Prysme"

DB_HOST="127.0.0.1"
DB_PORT="5432"

DB_USER="odoo"
DB_PASSWORD="Lmc14031703."

PSQL="/usr/lib/postgresql/17/bin/psql"
PG_DUMP="/usr/lib/postgresql/17/bin/pg_dump"
PG_RESTORE="/usr/lib/postgresql/17/bin/pg_restore"