# ============================================================
# Odoo Admin
# ============================================================

PRODUCT_NAME="Odoo Admin"
PRODUCT_VERSION="1.0"

PRODUCT_AUTHOR="Emmanuel Heredia"
PRODUCT_LICENSE="MIT"

ODOO_ADMIN_HOME="/opt/odoo-admin"

ODOO_ADMIN_CONFIG="${ODOO_ADMIN_HOME}/config"
ODOO_ADMIN_SCRIPTS="${ODOO_ADMIN_HOME}/scripts"
ODOO_ADMIN_LOGS="${ODOO_ADMIN_HOME}/logs"

ODOO_ADMIN_BACKUP="/var/backups/odoo"